// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/edu-whiteboard/Dashboard.tsx": () => import("../components/mockups/edu-whiteboard/Dashboard.tsx"),
  "./components/mockups/edu-whiteboard/Export.tsx": () => import("../components/mockups/edu-whiteboard/Export.tsx"),
  "./components/mockups/edu-whiteboard/Workspace.tsx": () => import("../components/mockups/edu-whiteboard/Workspace.tsx"),
  "./components/mockups/edu-whiteboard/WorkspaceDrawing.tsx": () => import("../components/mockups/edu-whiteboard/WorkspaceDrawing.tsx")
};
